0.0.1
PetkovDenis/BookCompany pull request #1
Opened 2024-07-12 23:06 UTC by PetkovDenis

2024-07-13 12:40 UTC, progressicu requested changes

2024-07-13 12:40 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/controller/BookController.java
> +        return new ResponseEntity<>(BookMapper.INSTANCE.toBookDTOList(bookService.allBooks()), HttpStatus.OK);
1. Переделай без ResponseEntity. Сейчас этим очень редко кто пользуется
2. Разберись как маппер можно встроить сразу в спринг как компонент. Подсказка - через pom.xml

2024-07-13 12:40 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/controller/BookController.java
> +    @Autowired
Лучше так не делать, автовайрить стоит через конструктор

2024-07-13 12:40 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/controller/BookController.java
> +    @GetMapping("/id")
А зачем тут маппинг?

2024-07-13 12:40 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/controller/BookController.java
> +        List<Book> books = bookService.allBooks().stream().filter(book -> book.getClient().getClientId().equals(clientId)).toList();
Если у тебя будет миллионы книг - будешь всех их доставать?

2024-07-13 12:40 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/service/facade/ClientBookFacade.java
> +public class ClientBookFacade {
С какой целью ты создавал этот класс?

2024-07-13 12:40 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/service/client/ClientServiceImpl.java
> +        return clientBookFacade.createBook(book);
Давай прочитаем код:
- метод "вернуть книгу". Подразумеваем что клиент возвращает уже созданную книга
- внутри метода вызываем "создать книгу" и передаем существующую книгу

Не кажется как-то странным?

2024-07-13 12:40 UTC, progressicu commented on target/classes/ru/petkov/bookcompany/BookCompanyApplication.class
всё что в таргет не должно быть в гите

2024-07-13 12:40 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/unit/TakeBookClientTest.java
> +        verify(clientRepository, times(1)).save(client);
строкой выше ты вызываешь сохранение и сейчас здесь проверяешь.
В чём смысл теста тогда?

2024-07-13 12:40 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/unit/CreateBookTest.java
> +        Book savedBook = bookService.createBook(book);
Хороший тест получился бы, но посмотри свой код.
Там хоть убери вообще вызов репозиторий у тебя всё равно тест пройдет, т.к. ты возвращаешь сразу аргумент который пришел в метод, а не то что вышло из репозитория (что должно быть)

2024-07-13 12:40 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/integration/ReturnBookTest.java
> +        mockMvc.perform(post("http://localhost:8080/client/return/2/1")
Как думаешь, если я запущу сразу этот тест у себя, то он у меня пройдет? Как сделать так, чтобы проходил всегда?

2024-07-13 12:40 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/integration/ReturnBookTest.java
> +        mockMvc.perform(post("http://localhost:8080/client/return/2/1")
аналогично к тесту выше

2024-07-13 13:15 UTC, PetkovDenis commented on src/main/java/ru/petkov/bookcompany/service/facade/ClientBookFacade.java
> +public class ClientBookFacade {
По идее, два сервиса выполняющие разную логику не должны пересекаться в коде. Т.е в ClientService не должно быть BookService или в ClientController BookRepositroy. Вот, по идее данный класс должен был выполнять логику в контроллерах без использования лишних сервисов.

2024-07-13 13:22 UTC, PetkovDenis commented on src/main/java/ru/petkov/bookcompany/service/client/ClientServiceImpl.java
> +        return clientBookFacade.createBook(book);
При вызове в BookRepository метод save(),  он будет либо создавать новый объект, или обновлять изменения в уже созданном. В нашем случае он удалит id клиента, тем самым обновит свое состояние.

2024-07-13 13:25 UTC, PetkovDenis commented on src/test/java/ru/petkov/bookcompany/controller/unit/TakeBookClientTest.java
> +        verify(clientRepository, times(1)).save(client);
Чтобы убедиться, что метод был вызван. Я согласен, не логично. Придумаю другой вид проверки

2024-07-13 13:28 UTC, PetkovDenis commented on src/test/java/ru/petkov/bookcompany/controller/integration/ReturnBookTest.java
> +        mockMvc.perform(post("http://localhost:8080/client/return/2/1")
Скорее всего не пройдет, тк не подключена бд.

2024-07-13 13:33 UTC, PetkovDenis commented on src/main/java/ru/petkov/bookcompany/controller/BookController.java
> +        List<Book> books = bookService.allBooks().stream().filter(book -> book.getClient().getClientId().equals(clientId)).toList();
Если у клиента много книг, то да. Иначе нет

2024-07-14 06:47 UTC, PetkovDenis commented on src/main/java/ru/petkov/bookcompany/service/client/ClientServiceImpl.java
> +        return clientBookFacade.createBook(book);
Изменил вызов метода на update

2024-07-16 12:09 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/service/facade/ClientBookFacade.java
> +public class ClientBookFacade {
Как бы да, но посмотри на своё применение - ты по факту вызов спрятал за лишним кодом.
Так тоже нельзя делать, т.к. приводит к тому же самому. Тут наоборот надо было, создавать промежуточный не слой между двумя сервисами, а сделать слой над ними

2024-07-16 12:17 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/controller/BookController.java
> +        return "Book was deleted";
зачем строку возвращаешь?

2024-07-16 12:17 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/controller/BookController.java
>      public UUID getRandomId() {
почему public остался

2024-07-16 12:17 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/controller/BookController.java
> +        List<Book> books = bookService.allBooks().stream().filter(book -> book.getClient().getClientId().equals(clientId)).toList();
я имел ввиду из бд. Про bookService.allBooks()

2024-07-16 12:17 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/controller/ClientController.java
> +    public ClientController(ClientService clientService, ClientBookFacade clientBookFacade, ClientMapper clientMapper, BookMapper bookMapper) {
используй lombok

2024-07-16 12:17 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/controller/ClientController.java
> +        return clientDTO;
ты создал клиента, а откуда получатель узнает его id, чтобы передать в других запросах?

2024-07-16 12:17 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/controller/ClientController.java
> +        return clientDTO;
должны быть входные, который приходят в твой сервис и выходные дто. которые отправляешь в ответ

2024-07-16 12:20 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/service/client/ClientServiceImpl.java
> +        return clientBookFacade.createBook(book);
Лучше от этого не стало. Сервис должен работать только с одним классом модели и всё, никак не с другими даже через промежуточные.
Бывают конечно исключение, но когда ты до них дойдешь, ты поймешь уже, пока это рано ещё

2024-07-16 12:21 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/integration/ListBookTest.java
> +
Лишние пропуски убирай. Код должен быть красивым

2024-07-16 12:22 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/integration/ListBookTest.java
> +    @BeforeEach
я буду запускать тесты все сразу. Как думаешь когда тогда проблема проявится?

2024-07-16 12:23 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/integration/ListBookTest.java
> +    public void testListBook() throws Exception {
почему метод так называется?

2024-07-16 12:25 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/integration/ListBookTest.java
> +        assertThat(result).isNotNull();
если isNotNull, то где дальше проверка, что вернется?
если ничего не возвращается, то также нужно проверять, что в бд всё правильно сохранилось. Подумай как это можно сделать (можно вручную, а можно такую либу как database-rider использовать)

2024-07-16 12:28 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/service/book/BookServiceImpl.java
> +        bookRepository.save(book);
дам прямую подсказку. Если что-то сохраняешь, то надо возвращать то, что возвращает репозиторий, а не то что в аргументах пришло. 
За тебя конечно spring подумал и сделал защиту от незнания этого, но в других фреймворках/языках будет от этого проблемы

2024-07-16 12:28 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/unit/CreateBookTest.java
> +        Book savedBook = bookService.createBook(book);
не исправил - что я имел ввиду, написал [здесь](https://github.com/PetkovDenis/BookCompany/pull/1/files#r1679302030)

2024-07-18 12:45 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/integration/BorrowedBookTest.java
> +        bookService.deleteBook(2L);
а почему удаляем вторую книгу, если в beforeEach создаем только одну?

2024-07-18 12:45 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/integration/BorrowedBookTest.java
> +                .andExpect(jsonPath("$[0].title").value("title5"))
Название теста и то что выполняется внутри - взять книгу.
А проверяешь везде наименование и автора. Надо проверять то что изменяется в том числе

2024-07-18 12:45 UTC, progressicu commented on target/generated-sources/annotations/ru/petkov/bookcompany/dto/mapper/BookMapperImpl.java
снова таргет

2024-07-18 12:45 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/unit/TakeBookClientTest.java
> +    void testTakeBookClient() {
а зачем приставку test в начале название метода добавил?

2024-07-18 12:45 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/unit/TakeBookClientTest.java
> +        Book book1 = clientService.takeBook(clientRepository.findById(client.getClientId()).get().getClientId(), book.getId());
зачем ты через репозиторий достаешь clientId?

2024-07-18 23:47 UTC, PetkovDenis commented on src/test/java/ru/petkov/bookcompany/controller/unit/TakeBookClientTest.java
> +    void testTakeBookClient() {
Я читал, что в названиях классов приставка test должна быть в конце, у методов в начале. Разве не так?

2024-07-20 03:58 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/service/client/ClientService.java
> +//    Book takeBook(Long clientId, Long bookId);
лишние комменты удаляй

2024-07-20 03:58 UTC, progressicu commented on src/main/java/ru/petkov/bookcompany/service/facade/ClientBookFacade.java
> +public class ClientBookFacade {
Вот теперь лучше 👍

2024-07-20 04:01 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/integration/ReturnBookTest.java
> +        clientBookFacade.returnBook(book.getId());
зачем ты это тут вызываешь?

2024-07-20 04:07 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/unit/CreateBookTest.java
> +    public void createBook() {
давай оставлю пример, а ты из него поймешь как следует делать юнит тесты (не обращай на подсветку ошибок, IDE ещё не успела просто всё прогрузить)
![image](https://github.com/user-attachments/assets/d62473ec-e2ec-414d-9e8c-6d11b4ae712c)

2024-07-21 11:28 UTC, progressicu commented on src/test/java/ru/petkov/bookcompany/controller/unit/TakeBookClientTest.java
>          when(clientBookFacade.takeBook(client.getClientId(), book.getId())).thenReturn(book);
ты мокаешь вызов и потом же его в act вызываешь - неправильно

2024-07-28 06:42 UTC, merged